### ISSUE TITLE
MAU 

### ISSUE THREAD

**Issue by rougegoat** [pbowden-msft/Payloads#5]
I'm not sure where the error is, but something in this section that is supposed to register the MAU for auto-updates is not currently working.  MAU 4.16 is available, but doesn't get detected on 4.15 with this current setup.

`
		<key>/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app</key>
		<dict>
			<key>Application ID</key>
			<string>MSau04</string>
			<key>LCID</key>
			<integer>1033</integer>
		</dict>
`

**Comment by pbowden-msft** [comment]
@rougegoat while MAU 4.16 is available, it is for *optional* download. The collateral files on the CDN are currently only enforcing MAU 4.15 as the latest mandated version. Usually, we bump the enforcement to the latest MAU version around the middle of each month (well, last Sunday of month + 18 days to be precise), but there are some issues with the new UX refresh in 4.16 that is causing us to hold back on making it mandatory for everyone.
